### ISSUE TITLE
verify if it's working

### ISSUE THREAD

**Issue by ghost** [xHN35RQ/sublime-notelink#1]
see: https://github.com/dansheffler/MyWiki/issues/1#issuecomment-193023755

It's been awhile since I tested this plugin (I use don't use sublime) and need to re-test to make sure everything is working well.

**Comment by ghost** [comment]
@lukaskawerau Works well for me with stock Sublime Text 3, installed via [Package Control](http://packagecontrol.io/). Also installed the Bracketeer plugin. Typing two `[` pulls up a quick filter menu of all files in current folder, and `Ctrl+Enter` on a link opens that file for editing.

**Comment by mjknght** [comment]
Still working for me, too. (Autocomplete disabled!)

**Comment by ghost** [comment]
I actually like this functionality so much, I'm going to eventually port it over to an Atom plugin.

**Comment by lukaskawerau** [comment]
Hm, this is weird.

Here's what I did: 
- uninstalled Sublime Text 3 (I also removed the folder in Application Support)
- reinstalled Sublime Text
- installed Package Control
- installed Bracketeer (via Package Control)
- installed sublime-notelink (via Package Control: Add Repository, Install Package)
- Sublime Text told me that the installation was successful and lists it under installed packages

But this still doesn't work.  
Interestingly, when I type [[, it auto-completes one of them (so I get this: [[]) and places the cursor in the middle. When I type anything then (like [[a]) it autocompletes the second bracket (so I get [[a]]) but there is no quick filter menu or anything.  

I didn't have any TE snippets that used brackets, but disabled TE regardless. Also changed nothing.

I even tried forking it to see if it was an issue of the path to the folder contained in the settings file and changed that, but that didn't help either. I have no clue what's going on here :/

@mjknght: which which autocomplete are you talking about? Do you mean TE or some other autocomplete that I haven't taken into account?

**Comment by ghost** [comment]
Hmm that's odd. Which version of Mac OS X are you using?

**Comment by lukaskawerau** [comment]
I'm using El Capitan, 10.11.3

**Comment by ghost** [comment]
Please try opening the console, and then typing `[` and see if anything shows in the console as an error.

**Comment by mjknght** [comment]
How strange! I now fear I may have forgotten tweaking something in order to make this work.

Yes, I was thinking of TE, although in Default (OS X).sublime-keymap you will find a section, "// Auto-pair square brackets", which you could temporarily remove to see whether that solves the problem. 

Another thing to add at this point is that I am using the October commit – https://github.com/xHN35RQ/sublime-notelink/commit/4dfbba45587015284e0374b1c783b4726d01f520 – which has a different name, etc. Could it be that something has crept in that OS X does not like?

**Comment by ghost** [comment]
@mjknght On Linux using a stock install of Sublime Text `//Auto-pair square brackets` is enabled and it works fine with the wiki-link functionality, so it feels like an OS X issue of some kind. The only code changes since the commit you reference are function and file re-names. I double-checked and there are code changes besides that.

**Comment by mjknght** [comment]
Thanks @xHN35RQ. If there are no changes, I wonder what the issue is… To be clear, that auto-pair is enabled for me in OS X as well – and mine is working. Also on 10.11.3. I do wonder if there's another auto-pair at work – @lukaskawerau you're not using [AutoPairs](http://www.jwwalker.com/pages/autopairs.html) or similar, are you?

**Comment by lukaskawerau** [comment]
So this is what I get when I type in the Sublime console:  

```
>>> [[
  File "<string>", line 1
    [[
     ^
SyntaxError: unexpected EOF while parsing
>>> [
  File "<string>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing
```

Does that help at all? This only appears when I hit Enter and shows the same for typing `{`or `-` as well...

@mjknght: Nope, not using AutoPairs or anything similar.

**Comment by ghost** [comment]
Sorry for not being clearer. I meant open the console, then move back up into the editor and type the square brackets, and watch the console to see if Sublime Text throws any errors.

**Comment by lukaskawerau** [comment]
Ah. Nope, nothing either :/

**Comment by ghost** [comment]
hmmm... maybe an issue with Bracketeer?? Sorry, I don't have a Mac to test on.

BTW, I've been toying with the idea of re-writing this plugin to eliminate the Bracketeer requirement and use the built-in Sublime Text [completion API](http://docs.sublimetext.info/en/latest/extensibility/completions.html#sources-for-completions-and-their-priorities). This way the filenames would appear inline with the text as you type.

**Comment by lukaskawerau** [comment]
Seems like the most probable cause, yeah. Thank you for spending so much time trying to help out!  

I would **definitely** use that, if you would build it!

**Comment by ghost** [comment]
Yeah, it does seem like a useful thing to build.
