### ISSUE TITLE
rewrite using native Sublime functionality

### ISSUE THREAD

**Issue by ghost** [xHN35RQ/sublime-notelink#2]
Combining the following native Sublime Text functionalities seems useful.

**note insertion**

Sublime has a completion API:
- http://docs.sublimetext.info/en/latest/extensibility/completions.html
- http://docs.sublimetext.info/en/latest/reference/api.html#sublime_plugin.EventListener.on_query_completions

Several plugins exist which provide filename completion and insertion, perhaps reference these for writing the plugin.

**note follow**

It also has a built-in command to expand the current selection to surrounding brackets:

> expand_selection
>    Extends the selection up to predefined limits.
>        to [Enum]: Values: bol, hardbol, eol, hardeol, bof, eof, brackets, line, tag, scope, indentation.
> http://docs.sublimetext.info/en/latest/reference/commands.html

Act on the selection to add a file extension and either open the file in Sublime, or create a new file at that location.

**Comment by xHN35RQ** [comment]
I'm no longer interested in writing a plugin for a text editor I don't use.
